--
-- STAR-Fusion 1.11.1 modulefile
--
-- "URL: https://www.psc.edu/resources/software"
-- "Category: Biological Sciences"
-- "Description: STAR-Fusion is a component of the Trinity Cancer Transcriptome Analysis Toolkit (CTAT). STAR-Fusion uses the STAR aligner to identify candidate fusion transcripts supported by Illumina reads. STAR-Fusion further processes the output generated by the STAR aligner to map junction reads and spanning reads to a reference annotation set."
-- "Keywords: singularity bioinformatics"

whatis("Name: STAR-Fusion")
whatis("Version: 1.11.1")
whatis("Category: Biological Sciences")
whatis("URL: https://www.psc.edu/resources/software")
whatis("Description: STAR-Fusion is a component of the Trinity Cancer Transcriptome Analysis Toolkit (CTAT). STAR-Fusion uses the STAR aligner to identify candidate fusion transcripts supported by Illumina reads. STAR-Fusion further processes the output generated by the STAR aligner to map junction reads and spanning reads to a reference annotation set.")

help([[
STAR-Fusion is a component of the Trinity Cancer Transcriptome Analysis Toolkit (CTAT). STAR-Fusion uses the STAR aligner to identify candidate fusion transcripts supported by Illumina reads. STAR-Fusion further processes the output generated by the STAR aligner to map junction reads and spanning reads to a reference annotation set.

To load the module, type

> module load STAR-Fusion/1.11.1

To unload the module, type

> module unload STAR-Fusion/1.11.1

Documentation
-------------
https://github.com/STAR-Fusion/STAR-Fusion/wiki

For help, type

> STAR-Fusion --help

Repository
----------
https://github.com/STAR-Fusion/STAR-Fusion

Tools included in this module are

* STAR-Fusion
* FusionInspector
* FusionAnnotator
* blast_and_promiscuity_filter.pl
]])

local package = "STAR-Fusion"
local version = "1.11.1"
local base    = pathJoin("/opt/packages",package,version)
prepend_path("PATH", base)
